spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:weatherdb
  h2:
    console:
      enabled: true
  config:
    import: optional:file:.env[.properties]
weather-stack:
  api-url: http://api.weatherstack.com/current
  api-key: ${API_KEY:default}
  cache-name: weathers
  api-call-limit: 30
  cache-ttl: 10000

resilience4j:
  ratelimiter:
    instance:
      basic:
        limit-for-period: 10
        limit-refresh-period: 1m
        timeout-duration: 10s

